spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learn?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.learn.dao.bean
  redis:
    host: 127.0.0.1
    port: 6379