server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    # 不注册自己
    registerWithEureka: false
    #不拉取服务
    fetchRegistry: false
    # EurekaServer的地址，现在是自己的地址，如果是集群，需要写其它Server的地址。
    serviceUrl:
      #注册的地址，如果是集群，应该用,隔开
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eurka-server